#!/usr/bin/env python3
"""
Generate the lazy variants of fleetctl/app_eager.py.

  app_lazy.py          every import in the IMPORTS block gets the 3.15 `lazy` keyword
                       (PEP 810). A SyntaxError on 3.14 and earlier.
  app_lazy_modules.py  the import block is untouched; a __lazy_modules__ list names the
                       modules to defer. On 3.14 and earlier it is an ordinary unused
                       variable, so the same file runs everywhere - the migration path.

    python3 scripts/make_variants.py          # write
    python3 scripts/make_variants.py --check  # fail if the committed files are stale
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "fleetctl"
SOURCE = ROOT / "app_eager.py"
START = "# --- IMPORTS"
END = "# --- END IMPORTS"
HEADER = "# GENERATED by scripts/make_variants.py from app_eager.py - do not edit.\n"


def split(text: str) -> tuple[str, list[str], str]:
    head, rest = text.split(START, 1)
    block, tail = rest.split(END, 1)
    first_line, *lines = block.splitlines(keepends=True)
    return head + START + first_line, lines, END + tail


def lazy_keyword(text: str) -> str:
    head, lines, tail = split(text)
    lines = [re.sub(r"^(import |from )", r"lazy \1", line) for line in lines]
    return HEADER + head + "".join(lines) + tail


def lazy_modules(text: str) -> str:
    head, lines, tail = split(text)
    modules = []
    for line in lines:
        if m := re.match(r"^import ([\w.]+)", line):
            modules.append(m.group(1))
        elif m := re.match(r"^from ([\w.]+) import", line):
            modules.append(m.group(1))
    declaration = "__lazy_modules__ = [\n" + "".join(f'    "{name}",\n' for name in modules) + "]\n"
    return HEADER + head + declaration + "".join(lines) + tail


def main() -> int:
    source = SOURCE.read_text()
    outputs = {
        ROOT / "app_lazy.py": lazy_keyword(source),
        ROOT / "app_lazy_modules.py": lazy_modules(source),
    }
    check = "--check" in sys.argv
    stale = []
    for path, content in outputs.items():
        if check:
            if not path.exists() or path.read_text() != content:
                stale.append(path.name)
        else:
            path.write_text(content)
            print(f"wrote {path.relative_to(ROOT.parent)}")
    if stale:
        print(f"stale: {', '.join(stale)} - run scripts/make_variants.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
