spring:
  application:
    name: liquibase-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/migration_demo
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
