#!/usr/bin/env python3
"""
Generate manifests/*.yaml - the four scenarios differ only in where the limits
live and whether the sidecar is busy, so they are generated from one template
to keep everything else identical. Mirrors scripts/emulate-docker.sh.

    python3 scripts/gen-manifests.py
"""
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "manifests"

POD_RESOURCES = """  resources:
    requests: {cpu: "1", memory: 1Gi}
    limits: {cpu: "1", memory: 1Gi}
"""

SCENARIOS = [
    {
        "name": "01-container-limits",
        "comment": ["Baseline: every container has its own limit, the way pods are sized today.",
                    "The JVM sizes its heap from its own 1 GiB limit; the sidecar is boxed at 64 MiB."],
        "pod": False,
        "app": '      resources:\n        requests: {cpu: "1", memory: 1Gi}\n        limits: {cpu: "1", memory: 1Gi}\n',
        "sidecar": "      resources:\n        limits: {cpu: 100m, memory: 64Mi}\n",
        "busy": False,
    },
    {
        "name": "02-pod-level-only",
        "comment": ["Pod-level budget (1 CPU / 1 GiB) and no container limits. Per KEP-2837 the kubelet sets",
                    "each unlimited container's cgroup limit to the pod limit, so the JVM sees 1 GiB.",
                    "The sidecar is idle, so the JVM really does have almost all of it."],
        "pod": True, "app": "", "sidecar": "", "busy": False,
    },
    {
        "name": "03-pod-level-only-busy-sidecar",
        "comment": ["Same as 02, but the sidecar is holding 384 MiB. The JVM still sees 1 GiB and sizes its",
                    "heap to 75% of it - but the pod cgroup only has ~640 MiB left for it."],
        "pod": True, "app": "", "sidecar": "", "busy": True,
    },
    {
        "name": "04-pod-level-plus-app-limit-busy-sidecar",
        "comment": ["Pod-level budget for everything, plus a container limit on the JVM only. The JVM sizes",
                    "itself from 640 MiB; the sidecar can still use whatever the app leaves free."],
        "pod": True,
        "app": '      resources:\n        limits: {cpu: "1", memory: 640Mi}\n',
        "sidecar": "", "busy": True,
    },
]


def render(s: dict) -> str:
    sidecar_cmd = ("dd if=/dev/zero of=/hog/fill bs=1M count=384 && touch /hog/ready && "
                   "while true; do sleep 5; done") if s["busy"] else "touch /hog/ready && while true; do sleep 5; done"
    return (
        "".join(f"# {line}\n" for line in s["comment"])
        + "# GENERATED by scripts/gen-manifests.py\n"
        + "apiVersion: v1\nkind: Pod\nmetadata:\n"
        + f"  name: {s['name'][3:]}\n  labels: {{scenario: {s['name'][3:]}}}\n"
        + "spec:\n  restartPolicy: Never\n"
        + (POD_RESOURCES if s["pod"] else "")
        + "  initContainers:\n"
        + "    # Native sidecar (restartPolicy: Always): shares the pod budget, stops when the app exits.\n"
        + "    - name: log-shipper\n      image: busybox:1.37\n      restartPolicy: Always\n"
        + f'      command: ["sh", "-c", "{sidecar_cmd}"]\n'
        + s["sidecar"]
        + "      # A native sidecar's startupProbe gates the app container: the JVM starts only after\n"
        + "      # the sidecar is holding its memory.\n"
        + "      startupProbe:\n        exec: {command: [\"test\", \"-f\", \"/hog/ready\"]}\n"
        + "        periodSeconds: 1\n        failureThreshold: 60\n"
        + "      volumeMounts:\n        - name: hog\n          mountPath: /hog\n"
        + "  containers:\n    - name: app\n      image: eclipse-temurin:25-jdk\n"
        + '      command: ["java", "/probe/ResourceProbe.java", "allocate"]\n'
        + "      env:\n        - name: CONTAINER_NAME\n          value: app\n"
        + "        # What most production JVM images set: heap = 75% of whatever memory the JVM can see.\n"
        + '        - name: JAVA_TOOL_OPTIONS\n          value: "-XX:MaxRAMPercentage=75"\n'
        + s["app"]
        + "      volumeMounts:\n        - name: probe\n          mountPath: /probe\n"
        + "  volumes:\n    - name: probe\n      configMap:\n        name: resource-probe\n"
        + "    # In-memory scratch space; tmpfs pages are charged to the container that writes them.\n"
        + "    - name: hog\n      emptyDir: {medium: Memory, sizeLimit: 512Mi}\n"
    )


def main() -> None:
    OUT.mkdir(exist_ok=True)
    for s in SCENARIOS:
        path = OUT / f"{s['name']}.yaml"
        path.write_text(render(s))
        print(f"wrote {path.relative_to(OUT.parent)}")


if __name__ == "__main__":
    main()
