package com.stevenpg.grpc.storefront.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.grpc.client.GrpcChannelFactory;

import com.stevenpg.grpc.inventory.proto.InventoryServiceGrpc;

import io.grpc.ManagedChannel;

/**
 * Builds the gRPC stubs the REST layer injects.
 *
 * <p>The pieces involved, outermost first:
 *
 * <ul>
 *   <li><b>Channel</b> - a managed, long-lived virtual connection to a
 *       target. It owns HTTP/2 connections, reconnection/backoff, load
 *       balancing and TLS. Channels are expensive: create ONE per target
 *       service and share it across the whole application. (Never create a
 *       channel per request - that is the #1 gRPC performance mistake.)</li>
 *   <li><b>Stub</b> - a lightweight, immutable, thread-safe view over a
 *       channel, generated by protoc. Stubs are cheap; the {@code with*}
 *       methods (deadline, metadata, compression) return NEW stubs, which
 *       is why per-call deadlines are applied in the controller and not
 *       baked in here.</li>
 * </ul>
 *
 * <p>The {@link GrpcChannelFactory} (autoconfigured by Boot 4.1's gRPC
 * client starter) resolves the name "inventory" against configuration -
 * see {@code spring.grpc.client.channel.inventory} in application.yml -
 * and applies every {@code @GlobalClientInterceptor} bean to the channels
 * it creates.
 *
 * <p>Alternative worth knowing: instead of declaring stub beans manually,
 * {@code @ImportGrpcClients(target = "inventory", types = ...)} registers
 * them for you. The explicit version below shows what actually happens.
 */
@Configuration(proxyBeanMethods = false)
public class GrpcClientConfig {

    /**
     * The blocking stub: one thread, one call at a time. Ideal inside a
     * servlet-based MVC app for unary calls, and it exposes server streams
     * as a plain {@link java.util.Iterator}.
     */
    @Bean
    InventoryServiceGrpc.InventoryServiceBlockingStub inventoryBlockingStub(GrpcChannelFactory channels) {
        ManagedChannel channel = channels.createChannel("inventory");
        return InventoryServiceGrpc.newBlockingStub(channel);
    }

    /**
     * The async stub: callback-based via {@link io.grpc.stub.StreamObserver}.
     * REQUIRED for client-streaming and bidirectional RPCs (a blocking API
     * cannot express "send messages while receiving"), and the right tool
     * for fanning server streams out to SSE, as the controller does.
     */
    @Bean
    InventoryServiceGrpc.InventoryServiceStub inventoryAsyncStub(GrpcChannelFactory channels) {
        // Same channel name -> Spring gRPC reuses the same underlying
        // channel; we are NOT opening a second connection.
        ManagedChannel channel = channels.createChannel("inventory");
        return InventoryServiceGrpc.newStub(channel);
    }
}
