// Command report prints the verified v1-vs-v2 behavioural differences as a
// table. The blog post's table is generated by this command, not typed by hand.
package main

import (
	"fmt"
	"strings"

	"github.com/StevenPG/demos/go-1-27-json-v2/internal/differences"
)

func main() {
	fmt.Println("encoding/json (v1) vs encoding/json/v2 -- observed on Go 1.27.1")
	fmt.Println(strings.Repeat("=", 78))

	for i, c := range differences.Cases() {
		fmt.Printf("\n%d. %s  [%s]\n", i+1, c.Name, c.Severity)
		fmt.Printf("   %s\n\n", wrap(c.Why, 3))
		fmt.Printf("   v1:     %s\n", render(c.V1()))
		fmt.Printf("   v2:     %s\n", render(c.V2()))
		fmt.Printf("   pinned: %s\n", render(c.Pin()))
		fmt.Printf("   via:    %s\n", c.PinDesc)
	}

	fmt.Printf("\n%s\n", strings.Repeat("=", 78))
	fmt.Println("Severity: \"error\"  = v2 fails loudly; you find out immediately.")
	fmt.Println("          \"silent\" = v2 succeeds with different data. Audit these first.")
}

func render(s string, err error) string {
	if err != nil {
		return "ERROR: " + err.Error()
	}
	return s
}

func wrap(s string, indent int) string {
	const width = 72
	words := strings.Fields(s)
	var b strings.Builder
	col := 0
	for _, w := range words {
		if col > 0 && col+len(w)+1 > width {
			b.WriteString("\n" + strings.Repeat(" ", indent))
			col = 0
		} else if col > 0 {
			b.WriteString(" ")
			col++
		}
		b.WriteString(w)
		col += len(w)
	}
	return b.String()
}
