package com.stevenpg.ffm;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;

/**
 * =====================================================================
 * SystemCallExamples - POSIX System Calls via FFM (Pure Java!)
 * =====================================================================
 *
 * This class calls the EXACT SAME system functions as the JNI example's
 * NativeSystemInfo class - but entirely in Java. No C code needed.
 *
 * SIDE-BY-SIDE COMPARISON:
 *
 *   To call gethostname() via JNI, you need:
 *     Java file:  public native String getHostname();
 *     C header:   (auto-generated by javac -h)
 *     C file:     JNIEXPORT jstring JNICALL Java_pkg_Class_getHostname(JNIEnv *env, jobject obj) {
 *                     char hostname[256];
 *                     gethostname(hostname, 256);
 *                     return (*env)->NewStringUTF(env, hostname);
 *                 }
 *     Build step: gcc -shared -fPIC -I$JAVA_HOME/include ... -o libfoo.so
 *
 *   To call gethostname() via FFM:
 *     Java only:  MethodHandle gh = linker.downcallHandle(lookup.find("gethostname").orElseThrow(),
 *                     FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_LONG));
 *                 gh.invoke(buffer, 256L);
 *     Build step: None! It's pure Java.
 *
 * WHY THIS MATTERS:
 *   - Faster development (no C compile step)
 *   - Easier debugging (everything is in Java, IDE support works)
 *   - Easier deployment (no platform-specific .so/.dylib to distribute)
 *   - Easier code review (one language, not two)
 *   - Lower barrier to entry (don't need C expertise on the team)
 */
public class SystemCallExamples {

    public static void run() {
        System.out.println("--- System Calls (POSIX functions via FFM) ---");

        Linker linker = Linker.nativeLinker();
        SymbolLookup stdlib = linker.defaultLookup();

        try {
            callGetHostname(linker, stdlib);
            callGetPid(linker, stdlib);
            demonstrateMallocFree(linker, stdlib);
            demonstrateErrnoCapture(linker, stdlib);
        } catch (Throwable e) {
            System.err.println("Error in system call examples: " + e.getMessage());
            e.printStackTrace();
        }

        System.out.println();
    }

    /**
     * Calls POSIX gethostname() - no C wrapper needed!
     *
     * C signature: int gethostname(char *name, size_t len)
     *   - name: buffer to write the hostname into
     *   - len: size of the buffer
     *   - returns: 0 on success, -1 on error
     *
     * This is one of the most compelling FFM examples because it shows
     * how you can call ANY C function from Java without writing C code.
     */
    private static void callGetHostname(Linker linker, SymbolLookup stdlib) throws Throwable {
        /*
         * Find gethostname in the standard library.
         *
         * On Linux, gethostname is in libc (included in defaultLookup).
         * On macOS, it's in libSystem (also included in defaultLookup).
         */
        MemorySegment gethostnameAddr = stdlib.find("gethostname")
                .orElseThrow(() -> new RuntimeException("gethostname not found"));

        /*
         * Describe the function signature.
         *
         * int gethostname(char *name, size_t len)
         *   → JAVA_INT return, ADDRESS param, JAVA_LONG param
         *
         * NOTE: size_t is mapped to JAVA_LONG because on 64-bit systems,
         * size_t is 8 bytes (same as Java's long). On 32-bit systems,
         * you'd use JAVA_INT instead. This is a platform consideration.
         */
        FunctionDescriptor desc = FunctionDescriptor.of(
                ValueLayout.JAVA_INT,    // return: int (0 on success)
                ValueLayout.ADDRESS,     // param 1: char *name (output buffer)
                ValueLayout.JAVA_LONG    // param 2: size_t len (buffer size)
        );

        MethodHandle gethostname = linker.downcallHandle(gethostnameAddr, desc);

        try (Arena arena = Arena.ofConfined()) {
            /*
             * Allocate a 256-byte buffer for the hostname.
             *
             * arena.allocate(256) allocates 256 bytes of zero-initialized
             * native memory. This is equivalent to calloc(1, 256) in C.
             *
             * We pass this buffer to gethostname(), which will write
             * the hostname string into it.
             */
            MemorySegment buffer = arena.allocate(256);

            /* Call gethostname(buffer, 256) */
            int result = (int) gethostname.invoke(buffer, 256L);

            if (result == 0) {
                /*
                 * buffer.getString(0) reads a null-terminated C string
                 * starting at byte offset 0 in the segment.
                 *
                 * This is equivalent to JNI's NewStringUTF(env, buffer),
                 * but doesn't require a JNIEnv* or any C code.
                 */
                String hostname = buffer.getString(0);
                System.out.println("Hostname:    " + hostname);
            } else {
                System.out.println("gethostname failed with code: " + result);
            }
        }
        /* Buffer is automatically freed when the arena closes */
    }

    /**
     * Calls POSIX getpid() - the simplest possible FFM system call.
     *
     * C signature: pid_t getpid(void)
     *   - Takes no parameters
     *   - Returns the process ID (an int)
     *   - Cannot fail
     */
    private static void callGetPid(Linker linker, SymbolLookup stdlib) throws Throwable {
        MemorySegment getpidAddr = stdlib.find("getpid")
                .orElseThrow(() -> new RuntimeException("getpid not found"));

        /*
         * FunctionDescriptor.of(JAVA_INT) = function returning int with no parameters.
         * This is the simplest possible function descriptor.
         */
        FunctionDescriptor desc = FunctionDescriptor.of(ValueLayout.JAVA_INT);
        MethodHandle getpid = linker.downcallHandle(getpidAddr, desc);

        /*
         * Invoke with no arguments. No Arena needed because there's no
         * native memory to manage - just a simple function call that
         * returns a primitive value.
         */
        int pid = (int) getpid.invoke();
        System.out.println("Process ID:  " + pid);
    }

    /**
     * Calls malloc() and free() directly from Java via FFM.
     *
     * This is the FFM equivalent of the JNI allocateAndReadNativeMemory example.
     * It demonstrates that FFM can call ANY C function, including memory
     * management functions.
     *
     * C signatures:
     *   void *malloc(size_t size)   - allocate memory
     *   void free(void *ptr)        - free memory
     *
     * NOTE: In practice, you'd use Arena-managed memory (much safer).
     * This example uses malloc/free directly to show:
     *   1. FFM can call these functions just like any other
     *   2. The manual approach is more error-prone (just like in C)
     *   3. Why Arena is preferred
     */
    private static void demonstrateMallocFree(Linker linker, SymbolLookup stdlib) throws Throwable {
        /*
         * Look up malloc and free.
         *
         * void *malloc(size_t size)  → returns ADDRESS, takes JAVA_LONG
         * void free(void *ptr)       → returns void, takes ADDRESS
         */
        MethodHandle malloc = linker.downcallHandle(
                stdlib.find("malloc").orElseThrow(),
                FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.JAVA_LONG)
        );

        MethodHandle free = linker.downcallHandle(
                stdlib.find("free").orElseThrow(),
                FunctionDescriptor.ofVoid(ValueLayout.ADDRESS)
        );

        String message = "FFM native memory test";
        byte[] bytes = message.getBytes();

        /*
         * Call malloc to allocate native memory.
         *
         * malloc returns a void* (ADDRESS in FFM). The MemorySegment we
         * get back has ZERO size (FFM doesn't know how big the allocation is).
         * We must call reinterpret() to tell FFM the actual size so it
         * can do bounds checking.
         *
         * This is one area where Arena-managed memory is clearly better:
         * arena.allocate() returns a properly-sized segment automatically.
         */
        MemorySegment ptr = ((MemorySegment) malloc.invoke((long) bytes.length + 1))
                .reinterpret(bytes.length + 1);  // Tell FFM the segment's actual size

        /*
         * Write the string bytes into native memory.
         *
         * MemorySegment.ofArray(bytes) creates a temporary segment backed by
         * the Java byte[] array. copyFrom() copies from it to our native buffer.
         * Then we write a null terminator at the end.
         */
        ptr.copyFrom(MemorySegment.ofArray(bytes));
        ptr.set(ValueLayout.JAVA_BYTE, bytes.length, (byte) 0);  // null terminator

        /* Read it back as a Java String */
        String readBack = ptr.getString(0);
        System.out.println("Native mem:  " + readBack);

        /*
         * Free the native memory.
         *
         * IMPORTANT: If we forget this call, the memory is leaked - just like
         * forgetting free() in C. FFM doesn't prevent this when you bypass
         * Arena and use malloc directly.
         *
         * Compare with Arena-managed memory where you CAN'T forget to free:
         *   try (Arena arena = Arena.ofConfined()) {
         *       MemorySegment buf = arena.allocate(size);
         *       // ... use buf ...
         *   } // automatically freed here, guaranteed
         */
        free.invoke(ptr);
    }

    /**
     * Demonstrates FFM's errno capture mechanism.
     *
     * Many C functions indicate errors by returning -1 and setting errno
     * (a thread-local error code). FFM can capture errno automatically
     * as part of the downcall, which is much cleaner than the JNI approach
     * of manually reading errno in C code.
     *
     * This calls open() with an invalid path to trigger an error,
     * then reads the captured errno to determine what went wrong.
     *
     * C signature: int open(const char *pathname, int flags)
     * On error: returns -1 and sets errno
     */
    private static void demonstrateErrnoCapture(Linker linker, SymbolLookup stdlib) throws Throwable {
        MemorySegment openAddr = stdlib.find("open")
                .orElseThrow(() -> new RuntimeException("open not found"));

        /*
         * Linker.Option.captureCallState("errno") tells FFM to capture
         * the value of errno after the native call returns.
         *
         * Without this option, errno might be overwritten by subsequent
         * operations before you can read it. FFM captures it atomically
         * as part of the return from the native function.
         *
         * In JNI, you'd have to read errno in your C wrapper function
         * immediately after the call and pass it back to Java manually.
         */
        StructLayout capturedState = Linker.Option.captureCallState("errno")
                .capturedStateLayout();

        FunctionDescriptor openDesc = FunctionDescriptor.of(
                ValueLayout.JAVA_INT,    // return: int (file descriptor or -1)
                ValueLayout.ADDRESS,     // param 1: const char *pathname
                ValueLayout.JAVA_INT     // param 2: int flags
        );

        MethodHandle open = linker.downcallHandle(openAddr, openDesc,
                Linker.Option.captureCallState("errno"));

        /*
         * Also look up strerror to convert errno to a human-readable message.
         * C signature: char *strerror(int errnum)
         */
        MethodHandle strerror = linker.downcallHandle(
                stdlib.find("strerror").orElseThrow(),
                FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.JAVA_INT)
        );

        try (Arena arena = Arena.ofConfined()) {
            /* Allocate space for the captured call state */
            MemorySegment state = arena.allocate(capturedState);

            /* Try to open a file that doesn't exist (O_RDONLY = 0) */
            MemorySegment badPath = arena.allocateFrom("/nonexistent/path/file.txt");
            int fd = (int) open.invoke(state, badPath, 0);

            if (fd == -1) {
                /*
                 * Read the captured errno from the call state.
                 *
                 * The capturedState layout has a field named "errno" that
                 * was populated by FFM when the native call returned.
                 */
                VarHandle errnoHandle = capturedState.varHandle(
                        MemoryLayout.PathElement.groupElement("errno"));
                int errnoValue = (int) errnoHandle.get(state, 0L);

                /* Convert errno to a human-readable message using strerror */
                MemorySegment msgPtr = ((MemorySegment) strerror.invoke(errnoValue))
                        .reinterpret(256);  // strerror returns a static string
                String errorMsg = msgPtr.getString(0);

                System.out.println("errno demo:  open() failed: errno=" + errnoValue
                        + " (" + errorMsg + ")");
            }
        }
    }
}
